### ISSUE TITLE
I can not install by luarocks!

### ISSUE THREAD

**Issue by csufangyu** [tomasguisasola/luasoap#17]
Hi ,
 I am so sorry to ask you! I can not install by luarocks,becuse I am lua5.1.and I want to install by source code,and how can i do?thanks very much!

**Comment by tomasguisasola** [comment]
I think you can install LuaSOAP with LuaRocks running on Lua 5.1.  Have you tried?  What happened?

LuaSOAP installation is very simple, since it is just a set of Lua files.  So, copy the files to /usr/local/share/lua/5.1/soap/.  Check the Makefile.  It could help you.

Since LuaSOAP depends on LuaExpat and on LuaSocket, you would have to install both packages too.

**Comment by csufangyu** [comment]
Yes I have trid to install by luarocks,but it filed.and the eerror is:
Error: Error fetching file: Failed downloading https://github.com/tomasguisasola/luasoap/archive/4.0.1.tar.gz - tlsv1 alert protocol version

**Comment by tomasguisasola** [comment]
Hi

The link is correct.  I think you have to install luasec don't you?

Regards,
Tomás

Em ter., 12 de mai. de 2020 às 00:41, universe <notifications@github.com>
escreveu:

**Comment by csufangyu** [comment]
oh great，thanks! it can work!-------- 原始邮件 --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年5月12日周二 晚上7:18收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [tomasguisasola/luasoap] I can not install by luarocks! (#17)

Hi



The link is correct.  I think you have to install luasec don't you?



Regards,

Tomás



Em ter., 12 de mai. de 2020 às 00:41, universe <notifications@github.com>

escreveu:
